version: '3.1'

services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-nfc-game
      MYSQL_USER: xenon
      MYSQL_PASSWORD: xenon
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro

  fast_api:
    build: ./fast_api
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./fast_api/:/app/
    depends_on:
      - mysqldb
    ports:
      - '8000:8000'
    restart: always

  react_app:
    build: ./nfc-app
    volumes:
      - ./nfc-app:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "yarn install && yarn start"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - fast_api