version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-nfc-game
      MYSQL_USER: xenon
      MYSQL_PASSWORD: xenon
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro